### ISSUE TITLE
When I install xfe, 

### ISSUE THREAD

**Issue by superigbt** [termux/proot-distro#11]
When I install xfe, execute
$ apt install xfe
  The error message is as follows:
dpkg: errors processing package libfpring-2-2:arm64(--configure):
dpkg: errors processing package gvfs:arm64(--configure):
dpkg: errors processing package fprintd(=1.90.1-1ubuntu1);
...
Errors were encountered while processing:
udisks2
gvfs-daemons
gvfs-backends
libfprint-2-2:arm64
gvfs:arm64
fprintd
libpam-fprintd:arm64
E:Sub-process /usr/bin/dpkg retuned an error code (1)

**Comment by Grimler91** [comment]
Please post the full error message. The part you posted does not show the actual error.

**Comment by bsde1234** [comment]
I also have this issue when run pkg install xfce4 on ubuntu prompt.
ˋˋˋ
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-backends:
 gvfs-backends depends on gvfs-daemons (= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs-backends (--configure):
 dependency problems - leaving unconfigured
Setting up libfprint-2-2:arm64 (1:1.90.2+tod1-0ubuntu1~20.04.1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                             Failed to scan devices: Permission denied
dpkg: error processing package libfprint-2-2:arm64 (--configure):
 installed libfprint-2-2:arm64 package post-installation script subprocess returned error exit status 1
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent configuration of gvfs:arm64:
 gvfs:arm64 depends on gvfs-daemons (<< 1.44.1-1ubuntu1.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:arm64 depends on gvfs-daemons (>= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:arm64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of fprintd:
 fprintd depends on libfprint-2-2 (>= 1:1.90.1); however:
  Package libfprint-2-2:arm64 is not configured yet.

dpkg: error processing package fprintd (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpam-fprintd:arm64:
 libpam-fprintd:arm64 depends on fprintd (= 1.90.1-1ubuntu1); however:
  Package fprintd is not configured yet.

No apport report written because MaxReports is reached already
                                                              No apport report written because MaxReports is reached already
     No apport report written because MaxReports is reached already
                                                                   dpkg: error processing package libpam-fprintd:arm64 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 libfprint-2-2:arm64
 gvfs:arm64
 fprintd
 libpam-fprintd:arm64
E: Sub-process /usr/bin/dpkg returned an error code (1)
ˋˋˋ

**Comment by michalbednarski** [comment]
`udisks2` is package providing handling of mounting and managing disks, which is not supported under proot.

While `udisks2` still won't work, you can unblock installation process by running following commands (after failed install, in guest system as root)
```
rm /var/lib/dpkg/info/udisks2.postinst
dpkg --configure -a
```

**Comment by bsde1234** [comment]
Now I have this error

```
Setting up libfprint-2-2:arm64 (1:1.90.2+tod1-0ubuntu1~20.04.1) ...
Failed to scan devices: Permission denied
dpkg: error processing package libfprint-2-2:arm64 (--configure):
 installed libfprint-2-2:arm64 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of fprintd:
 fprintd depends on libfprint-2-2 (>= 1:1.90.1); however:
  Package libfprint-2-2:arm64 is not configured yet.

dpkg: error processing package fprintd (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpam-fprintd:arm64:
 libpam-fprintd:arm64 depends on fprintd (= 1.90.1-1ubuntu1); however:
  Package fprintd is not configured yet.

dpkg: error processing package libpam-fprintd:arm64 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 libfprint-2-2:arm64
 fprintd
 libpam-fprintd:arm64
```

I dont have fingerprint reader in mobile

**Comment by michalbednarski** [comment]
I haven't seen this error before but it looks like relevant `postinst` script which is failing here is `/var/lib/dpkg/info/libfprint0:arm64.postinst` (So remove it and proceed as above)

`fprintd` cannot work in Android proot even with fingerprint reader, but that isn't really relevant since in usual usage desktop environment is being launched directly (bypassing login/display manager (like LightDM/GDM/...)).

**Comment by bsde1234** [comment]
Install went fine. Now  I have this error log for vnc

```
Xvnc TigerVNC 1.10.0 - built Apr  9 2020 06:49:31
Copyright (C) 1999-2019 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12008000, The X.Org Foundation


Mon Sep 21 07:13:58 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0
gpg-agent[7542]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent[7543]: gpg-agent (GnuPG) 2.2.19 started

(xfce4-session:7479): xfce4-session-WARNING **: 07:14:01.455: gpg-agent returned no PID in the variables

(xfce4-session:7479): xfce4-session-WARNING **: 07:14:01.482: xfsm_manager_load_session: Something wrong with /root/.cache/sessions/xfce4-session-localhost:1, Does it exist? Permissions issue?

(xfwm4:7544): xfwm4-WARNING **: 07:14:03.883: Unsupported GL renderer (llvmpipe (LLVM 10.0.0, 128 bits)).

(xfsettingsd:7580): libupower-glib-WARNING **: 07:14:04.277: Couldn't connect to proxy: Could not connect: No such file or directory

(xfsettingsd:7580): libupower-glib-CRITICAL **: 07:14:04.279: up_client_get_lid_is_closed: assertion 'UP_IS_CLIENT (client)' failed

(xfsettingsd:7580): GLib-GObject-WARNING **: 07:14:04.280: invalid (NULL) pointer instance

(xfsettingsd:7580): GLib-GObject-CRITICAL **: 07:14:04.281: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

** (agent:7628): CRITICAL **: 07:14:06.767: Failed to get connection to system bus: Could not connect: No such file or directory

** (xiccd:7625): CRITICAL **: 07:14:07.195: Failed to connect to colord: Could not connect: No such file or directory

(wrapper-2.0:7611): GLib-GIO-CRITICAL **: 07:14:08.012: g_file_new_for_path: assertion 'path != NULL' failed

(wrapper-2.0:7611): GLib-GIO-CRITICAL **: 07:14:08.014: g_file_monitor_file: assertion 'G_IS_FILE (file)' failed

(wrapper-2.0:7611): GLib-GObject-WARNING **: 07:14:08.016: invalid (NULL) pointer instance

(wrapper-2.0:7611): GLib-GObject-CRITICAL **: 07:14:08.016: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:7611): Gtk-WARNING **: 07:14:08.017: Attempting to add a widget with type GtkToggleButton to a container of type XfcePanelPlugin, but the widget is already inside a container of type XfcePanelPlugin, please remove the widget from its existing container first.

(wrapper-2.0:7615): libactions-WARNING **: 07:14:08.594: Calling CanShutdown failed GDBus.Error:org.xfce.SessionManager.Error.Failed: Could not connect: No such file or directory

(wrapper-2.0:7615): libactions-WARNING **: 07:14:08.671: Calling CanRestart failed GDBus.Error:org.xfce.SessionManager.Error.Failed: Could not connect: No such file or directory

(xfce4-session:7479): xfce4-session-WARNING **: 07:14:08.704: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:7479): xfce4-session-WARNING **: 07:14:08.755: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(nm-applet:7621): nm-applet-WARNING **: 07:14:08.799: Error connecting to system D-Bus: Could not connect: No such file or directory

(nm-applet:7621): nm-applet-WARNING **: 07:14:08.805: Could not connect: No such file or directory

(wrapper-2.0:7611): Gtk-WARNING **: 07:14:08.810: Negative content width -3 (allocation 1, extents 2x2) while allocating gadget (node button, owner GtkToggleButton)

(xfce4-session:7479): xfce4-session-WARNING **: 07:14:08.839: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.249: ((libnm/nm-client.c:3905)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.265: ((libnm/nm-client.c:3859)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.267: ((libnm/nm-client.c:3937)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.269: ((libnm/nm-client.c:3986)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.269: ((libnm/nm-client.c:4026)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.271: ((libnm/nm-client.c:4042)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.272: ((libnm/nm-client.c:4080)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.273: ((libnm/nm-client.c:4598)): assertion '<dropped>' failed

(nm-applet:7621): libnm-CRITICAL **: 07:14:09.276: ((libnm/nm-client.c:4598)): assertion '<dropped>' failed
system-config-printer-applet: failed to connect to system D-Bus

(xfdesktop:7598): GVFS-RemoteVolumeMonitor-WARNING **: 07:14:09.709: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

(wrapper-2.0:7610): Gtk-WARNING **: 07:14:10.417: Negative content width -3 (allocation 1, extents 2x2) while allocating gadget (node button, owner PulseaudioButton)

** (xfdesktop:7598): WARNING **: 07:14:10.896: Failed to get system bus: Could not connect: No such file or directory

Mon Sep 21 07:14:29 2020
 Connections: accepted: 127.0.0.1::44308
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
terminate called after throwing an instance of 'rdr::Exception'
terminate called recursively
(EE)
(EE) Backtrace:
(EE) 0: /usr/bin/Xtigervnc (OsLookupColor+0x188) [0x30001f6038]
(EE) unw_get_proc_info failed: no unwind info found [-10]
(EE)
(EE)
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE)
Gdk-Message: 07:14:29.607: light-locker: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.

Gdk-Message: 07:14:29.614: evolution-alarm-notify: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.

Gdk-Message: 07:14:29.610: wrapper-2.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.610: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.0.

Gdk-Message: 07:14:29.611: wrapper-2.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.610: wrapper-2.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.621: xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.620: xfwm4: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.620: xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.625: Thunar: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.625: wrapper-2.0: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.634: xfce4-session: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Gdk-Message: 07:14:29.629: xfce4-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
```

**Comment by xeffyr** [comment]
Try `vncserver -localhost -SecurityTypes None`.

**Comment by bsde1234** [comment]
@xeffyr That works.

**Comment by Saikatsaha1996** [comment]
> Try `vncserver -localhost -SecurityTypes None`.
Any solution for this ?

![Screenshot_2021-06-26-17-10-56-780_com termux](https://user-images.githubusercontent.com/72664192/123511851-84bd2880-d6a1-11eb-91e1-a4effff37470.jpg)
