### ISSUE TITLE
[Distribution]:Add Debian 11

### ISSUE THREAD

**Issue by trungtai33** [termux/proot-distro#132]
### Description

I want you to add Debian 11

### Home page URL

.

### Root file system archive URL

https://docker.debian.net/

**Comment by xeffyr** [comment]
In version 2.2.0 Debian is upgraded to 11 (bullseye). It will be available within few hours for installation. Thanks.

***

If using existing rootfs, you will need to upgrade it manually.

Otherwise (once you're on 2.2.0):
* New installations: `proot-distro install debian`
* Full re-installation: `proot-distro reset debian`
