### ISSUE TITLE
[Feature]: make --isolated default mode of operation to prevent hard-to-diagnose build errors

### ISSUE THREAD

**Issue by heavycrystal** [termux/proot-distro#184]
### Feature description

I've run into issues multiple times where build systems like CMake picks up a tool like bison from the Termux filesystem side (under /data/data/com.termux/usr/...) when the distro itself does not bundle the tool. While the configuration stage succeeds, the build itself is likely to fail because of different libcs at work, among other things. I'm not very sure why this happens to begin with since it's a non standard location, but the end result is errors that are very hard to isolate.

I understand this is probably an obscure use case, but I believe many users of proot-distro aren't even aware about the mounts under /data, and therefore never use the feature. I also feel that the mounts might also lead to accidental loss of data from the Termux filesystem. I therefore propose making "--isolated" [no transparent mounts from the Termux filesystem to the proot filesystem] as the default mode of proot-distro. 

I'm willing to make a PR on this issue if deemed necessary.

Thanks in Advance!

**Comment by xeffyr** [comment]
Please do not request to turn options into defaults. I understand that everyone wants to "type less", but such kind of change contradicts the project purpose. Isolated mode disables the mounting of all Android file systems and disables possibility of communicating with Termux environment as well as with shared storage.

PRoot Distro was never meant to provide isolated environment (similar to tools like `firejail`) but rather as utility to merge capabilities of Termux and Linux distributions.

You can set custom `PATH` variable in `~/.bashrc` to avoid picking of Termux tools. Alternatively you can edit `/etc/profile.d/termux-proot.sh`. Default `PATH` looks like this:
```
export PATH=${PATH}:/data/data/com.termux/files/usr/bin:/system/bin:/system/xbin
```

Everything else shouldn't cause side effects and `/data` mount won't affect distribution on its own because it is not part of FHS.

> I believe many users of proot-distro aren't even aware about the mounts under /data, and therefore never use the feature

At least some users are known use Termux:API under PRoot Distro. Lots of users accessing the shared storage via PRoot Distro. Finally, whether someone aware or not about mounts, that doesn't mean PRoot Distro won't play desire pleaser like more known proot management tool Andronix and unlike the latter, it has a stable design.

> I also feel that the mounts might also lead to accidental loss of data from the Termux filesystem

Well, preventing data loss is a one of the purposes of `--isolated` option. But that doesn't mean that it should be enabled by default. Usage of Termux itself or other apps can lead to data loss, but that doesn't mean they should be fool-proof, isn't it? If user executed `rm -rf --no-preserve-root /*` or script that will overwrite something, the lost data would be his own fault.

Think on what you are typing. If have doubts, use `--isolated`.

**Comment by heavycrystal** [comment]
Fair enough. Thanks for the succinct reply.
