### ISSUE TITLE
[Bug]: not able to redirect output to file

### ISSUE THREAD

**Issue by DeicPro** [termux/proot-distro#186]
### Problem description

When trying to redirect the output of proot-distro to a file, the output appears in terminal even with ">" and the file is empty.

### What steps will reproduce the bug?

Examples:
`proot-distro list > file`

`echo $(proot-distro list) > file`

`proot-distro list | tee file`

`echo $(proot-distro list) | tee file`

### What is the expected behavior?

Open the file a see the output of the proot-distro command, and in case of send via ">" don't see the output in the terminal.

### Extra

✅ I just discover that I'm not able redirect to a file with ">" at least because the output is stderr and ">" redirect only stdout, so I should use "&>" to redirect both stdout and stderr.

❌ Also using "grep" with a pipeline after of the proot-distro command doesn't work too.

**Comment by xeffyr** [comment]
Expected behavior. You have just discovered `stderr` - standard error output stream which is used instead of `stdout`.

https://github.com/termux/proot-distro/blob/94dff93c331ef5f4ec007b14e287a2a5cbde1bb2/proot-distro.sh#L69-L76

The output of any PRoot Distro commands (except the executed inside distribution) is not supposed to be piped. But if you really need that, do `proot-distro list >file 2>&1`.

**Comment by DeicPro** [comment]
`proot-distro list &> file` do the job like I said in the OP. Sadly i can't `tee` or `grep` the output directly by default. Well, I will locally edit the msg function and done.

Regards.

**Comment by ShivaShirsath** [comment]
```bash
proot-distro list | termux-clipboard-set
```
Copy it on clipboard & paste it into file
