### ISSUE TITLE
[Feature]: Enable visualisation

### ISSUE THREAD

**Issue by ShivaShirsath** [termux/proot-distro#224]
### Feature description

Enable visualisation for installing Emulator in Android studio for building applications.

Android studio says **key emulator not found**

As the by default installing the ubuntu it also wants to be enable. 

Please do a try !.
Thanks 😇

**Comment by wmcbtech30** [comment]
It's virtualization

This depends on your device that supports hardware virtualization to run VMs in a native speed. but since most Android devices have kvm disabled, you cannot use emulators but in a slower way which is using tcg and thus would require root and also disabling ARM trustzone which is reserved as a type-1 hypervisor and proot cannot simulate virtualization because it shares the same kernel as android.
