### ISSUE TITLE
provide possibility to run a command in the proot by preserving the host environment

### ISSUE THREAD

**Issue by ronnac** [termux/proot-distro#41]
This is a feature request.
I want to be able to run java in the normal termux session by using proot-distro login.
I want java to be able to access all host environment variables.
I am more or less able to achieve this by applying the following changes to proot-distro:

line 816 or so: change `su -l` to `su -p`
line 727 - 731 : comment out the whole `/usr/bin/env` section
line 753: comment out `set -- "--cwd=/root" "$@"
`
Create the script file "java" in ~/../usr/local/bin/ with the following content:

```
#!/usr/bin/bash
#UBUNTU=/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu-20.04
cd $PWD
prootexec login --termux-home \
 --shared-tmp \
 ubuntu-20.04 -- \
 /usr/bin/java "$@"
``` 
... and make it executable

also [see my comment on java in termux](https://github.com/termux/termux-packages/issues/324#issuecomment-729503160)
.  #40 #

**Comment by xeffyr** [comment]
Sorry, but no. Environment variables are being cleaned intentionally.

**Comment by ronnac** [comment]
I suggest to create a -p option (p for preserve) for "proot-distro login" so that users can decide if they want to allow environment preservation. The su command has this option, and I motivated my request. Could you give me a hint as to why you prefer not to implement this?

**Comment by xeffyr** [comment]
> Could you give me a hint as to why you prefer not to implement this?

a. `proot-distro` tends to provide a clean Linux distribution environment, free from Android. (yet it still create mounts for using `termux-api`). It is not a launch pad for Linux commands in Termux. On the first setup it configures all necessary environment variables: https://github.com/termux/proot-distro/blob/master/proot-distro.sh#L309-L325
b. Some environment variables must and will be overwritten or unset: PATH, LD_PRELOAD, LD_LIBRARY_PATH and others, potentially leading to clash between Android environment and GNU/Linux.

That's btw the reason why I prefer to use `su` for login, instead of running shell directly.

**Comment by xeffyr** [comment]
Fixing https://github.com/termux/proot-distro/issues/40 will be enough for overriding default login command and allow to pass custom environment variables.

**Comment by ronnac** [comment]
I haven't figured out how to do this, because some of my current environment variables contain spaces.

**Comment by ronnac** [comment]
Can you suggest a "launch pad for Linux commands" that would allow me to call java from the host?
