### ISSUE TITLE
[Question] Why use eu mirror of arch linux arm?

### ISSUE THREAD

**Issue by sainnhe** [termux/proot-distro#44]
https://github.com/termux/proot-distro/blob/ff9f3198c982fbec21bf4799750669fe38bc76a3/distro-plugins/archlinux.sh#L19-L24

Why use `eu.mirror.archlinuxarm.org` instead of `os.archlinuxarm.org`? IMO, it might be better to use the domain name of official download url.

**Comment by WMCB-Tech** [comment]
I think it's the file size:
![image](https://user-images.githubusercontent.com/65075766/101735495-f619fd00-3afc-11eb-9b6e-65860878ff19.png)

the https://eu.mirror.archlinuxarm.org has the less file size so i think it's preferred and save download time

**Comment by sainnhe** [comment]
The size is smaller simply because it's out of date.

The rootfs tarball in https://eu.mirror.archlinuxarm.org/os/ remains in 2018, while the tarball in http://os.archlinuxarm.org/os is 2020.

I think keeping the tarball up to date is much more important than making it as small as possible, since arch linux is a rolling release, too long update interval may cause update failure.

**Comment by sainnhe** [comment]
Btw, the x86 architecture uses `mirror.rackspace.com` which is also a mirror after all, I'd suggest you to use https://archive.archlinux.org/

https://github.com/termux/proot-distro/blob/ff9f3198c982fbec21bf4799750669fe38bc76a3/distro-plugins/archlinux.sh#L25-L32

**Comment by xeffyr** [comment]
*Why mirror?* Ok, here is an answer why you really should use a mirror (no matter EU, USA, or somewhere else):
* Reduce bandwidth on primary server. If everyone will not use a mirror, it will get down some day.
* Mirrors usually have higher DL speed, sometimes when their location is closer (that's why I choose EU mirror), sometimes because less people use it.

So, changing from the mirror to primary domain - that's a wontfix.

> The size is smaller simply because it's out of date

Ok, will fix that. However as ArchLinux (ARM) is a rolling-release distribution, a simple `pacman -Syu` will make it up-to-date.

> I think keeping the tarball up to date is much more important than making it as small as possible

I do not constantly monitor upstream changes made to tarballs.

If you want to change URL, tarball version or do other modifications, then navigate to `$PREFIX/etc/proot-distro` and make appropriate changes to distribution script. I provide defaults which may not be suitable for everyone, considering this issue.

***

All distro-plugins are editable by user since they are configuration files installed into `$PREFIX/etc/proot-distro`.

**Comment by sainnhe** [comment]
@xeffyr Yeah, you are right, it's reasonable not to use `archive.archlinux.org`.

But I still suggest to use `os.archlinuxarm.org`, because this is not a primary server, it will redirect to a mirror domain name based on your ip.

**Comment by xeffyr** [comment]
> it will redirect to a mirror domain name based on your ip.

Ah, ok will use it.
