### ISSUE TITLE
Run proot-distro as root

### ISSUE THREAD

**Issue by you** [termux/proot-distro#53]
Is it possible to run proot-distro as root? So the /sys, /proc, /dev is automatically mounted.

![IMG_20201227_232736](https://user-images.githubusercontent.com/57100752/103175291-77aeb080-489b-11eb-8372-ee28248cf8e7.jpg)

**Comment by xeffyr** [comment]
`proot-distro` is solely for non-root use.

**Why?** - Because `proot-distro` has a potential to annihilate everything on `/data` and possibly `/system` if something went wrong.

> So the /sys, /proc, /dev is automatically mounted.

I can't understand your statement on these mount points.

1. /sys, /proc, /dev are always mounted on Android OS.
2. They are bound by `proot` anyway.

If they are "not mounted automatically", then you have a device with some special Android OS build - this case is not supported officially, neither by `proot-distro` nor by Termux in general.

If you mean things like `/proc/stat`, then you can either put SELinux into permissive mode or change security label for such restricted files. No need to modify `proot-distro`.
