### ISSUE TITLE
Using chroot instead of proot on rooted phone

### ISSUE THREAD

**Issue by ICHx** [termux/proot-distro#76]
Hi,

I have a rooted phone, I find linux-deploy is more difficult to coupled with the host due to the lack of termux-api packages.  

How can I use proot-distro or termux to create ubuntu/chroot into existing chroot under ** termux**?

**Comment by WMCB-Tech** [comment]
> How can I use proot-distro or termux to create ubuntu/chroot into existing chroot using chroot?
Currently reusing `proot`'ed rootfs for `chroot` will cause problems about permissions and ownership, you will need to set them up from scratch

You could use existing `linux.img` file created with linux deploy and loop-mount it somewhere in Termux, then you do chroot

And Export some environment variables to get stuff working, but suggesting to run it as regular user
See Source code on how termux programs are runnable in `proot`'ed environment:
https://github.com/termux/proot-distro/blob/db8753c422eb6b09816edbc0f847fabe9798fe45/proot-distro.sh#L353

**Comment by xeffyr** [comment]
> How can I use proot-distro or termux to create ubuntu/chroot into existing chroot under

It would require rewriting proot-distro.

However I guess you have noticed that it named exactly `proot-distro`, not the `chroot-distro` or something more general like `linux-distro`. I would not work on the chroot variant. I don't have root and possibly never will have it because I don't need it. I won't work on any root-using feature (considering my devices are non-rooted, even if custom ROM has been installed). `proot-distro` has been started as rootless/safe `proot` wrapper and will remain be such.

There lots of examples on the Internet about `chroot` setup and usage. You can do it on your own.
