### ISSUE TITLE
dpkg --print-architecture

### ISSUE THREAD

**Issue by PickaxeHit** [termux/proot-distro#87]
My device is armv8l, and run it:
`dpkg --print-architecture`
`armhf`
After I executed those commands in the readme file, the problem still exists.
After executing dpkg --print-architecture in termux, aarch64 will be displayed

**Comment by xeffyr** [comment]
**Expected behavior.** `proot-distro` follows same logic for arch detection as Termux application.

armv8l means exactly these things:
* Your CPU is AArch64.
* Your Android OS is 32 bit.

You can't run 64 bit proot'ed environment with 32 bit `proot`. All Termux packages depend on Android libraries which are 32 bit only in your case.

True ARM 64 bit Android (Termux) installations show `aarch64` in `uname -a` and `dpkg --print-architecture` output.
