### ISSUE TITLE
Miss adding termux $PREFIX/lib to LD_LIBRARY_PATH on proot login

### ISSUE THREAD

**Issue by amsitlab** [termux/proot-distro#93]
![Screenshot_20210707-043008](https://user-images.githubusercontent.com/10000281/124669542-c0939180-dedc-11eb-88f7-59e60c84f01e.png)

to use all termux binary program on proot-distro session, we need add termux $PREFIX/lib to LD_LIBRARY_PATH manually .

It will be nice setting at login/binding process.

**Comment by xeffyr** [comment]
Sorry, won'tfix.

Why:
* LD_LIBRARY_PATH is not needed for Termux running on Android 7 or higher (if not using legacy environment). Moreover, it breaks things on up-to-date Termux, because we are now relying on DT_RUNPATH ELF section and LD_LIBRARY_PATH will override it. Note that `proot-distro` doesn't maintain compatibility with legacy environment (Termux on Android 5/6).
* You can't mix libraries from Termux and Linux distro due to ABI differences.

**Comment by amsitlab** [comment]
Alternativly, We can create executable file called as "termux.sh" oh chroot env, contains shell script like:
```sh
OLD=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$PREFIX/lib
exec "$@"
export LD_LIBRARY_PATH=$OLD
```

Then we can execute termux packages with ```termux.sh <pkgname>```

Like ```termux.sh nvim somefile```

**Comment by xeffyr** [comment]
We don't need LD_LIBRARY_PATH to execute Termux packages.

Era of Android 6 has been finished and `LD_LIBRARY_PATH` has been deprecated: https://github.com/termux/termux-app/commit/fc04a93990eae1ac8b78d216b853f753b93a7bcf. We now use `DT_RUNPATH` sections coded into ELF executables.

**Comment by xeffyr** [comment]
![Screenshot_20210711-183112](https://user-images.githubusercontent.com/25881154/125201101-57ae6f80-e276-11eb-9724-327e454d222d.png)

**Comment by amsitlab** [comment]
Ok, thank for you time.
