### ISSUE TITLE
Option to override `--kill-on-exit` from command line

### ISSUE THREAD

**Issue by santosh-d3vpl3x** [termux/proot-distro#94]
First of all, @xeffyr Thanks for all the great work :) I have tried proot with native android libs, I had limited success. But since I moved to termux with proot+proot-distro, it has been nothing but seamless.

I would like to request a way to override `--kill-on-exit` flag in `proot-distro`. Happy to submit a PR if you agree that this should be exposed outside.

**Comment by xeffyr** [comment]
--kill-on-exit is essential, so you will be able to exit from proot when background service is running.

Won'tfix as this is not optional proot configuration. Proot is not chroot.

**Comment by michalbednarski** [comment]
But this issue was about introducing `--no-kill-on-exit` argument for `proot-distro login`, similar to already existing `--no-sysvipc` and `--no-link2symlink` (All of these are opt-in features of `proot`, later two are opt-out features of `proot-distro` and here is request for opt-out for `--kill-on-exit`)

While `--kill-on-exit` is nice default (as e.g. `apt` can start background service and later user would be surprised by not regaining Termux shell after exiting from prooted shell, perceiving it as hang), as I understand this is what issue author wants

Just possibly this caveat about seeming hang should be shown in `proot-distro login` help text (or possibly left undocumented and discoverable only in `proot-distro` source)

Either way, I just think you should reconsider @xeffyr

**Comment by xeffyr** [comment]
Ok, I can add it as well as warning that will be shown if `--no-kill-on-exit` has been used.
